version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"
      - "9300:9300"

  minio:
    image: minio/minio
    depends_on:
      - elasticsearch
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/export
      - minio-config:/root/.minio
    entrypoint: >
      /bin/sh -c "
      curl https://raw.githubusercontent.com/nitisht/minio-compose/master/wait-for.sh -o wait-for.sh;
      curl https://raw.githubusercontent.com/nitisht/minio-compose/master/minio-elasticsearch/config.json -o /root/.minio/config.json;
      chmod +x wait-for.sh;
      ./wait-for.sh elasticsearch:9200 -- /usr/bin/docker-entrypoint.sh minio server /export;
      "

volumes:
  minio-data:
  minio-config: